### PR TITLE
Make CMP disableable and enableable

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

Adds helper exports to disable the CMP entirely in the current browser – other teams need this in their tests:

- `cmp.__enable()`
- `cmp.__disable()`
- `cmp.__isDisabled()`

The same can be achieved manually by setting/removing a cookie:

- `gu-cmp-disabled=true` 

cc @paulmr @rtyley @gtrufitt @coldlink

### CODE REVIEW

**Comment by jorgeazevedo** [comment]
This is going to be really useful to dotcom for running google lighthouse tests! Do you know when you intend to merge this?

**Comment by sndrs** [comment]
@jorgeazevedo hopefully today, or tomorrow if not – will let you know

**Comment by jorgeazevedo** [comment]
appreciated, thanks!

**Comment by davidfurey** [comment]
🎉  
Does frontend need to bump the version of this library for this feature to work  on fronts?

**Comment by mxdvl** [comment]
> Does frontend need to bump the version of this library for this feature to work on fronts?

Yes, and it's now live: https://github.com/guardian/frontend/pull/22929

**Pull request merged**
