### PR TITLE
Use Sourcepoint subdomain

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

The [latest documentation from Sourcepoint][sp-doc] on domain suggests to use our first-party domain name to improve performance and increase cookies' lifetime in Safari.

- TCFv2 config is simplified into a single `baseEndpoint` set to sourcepoint.theguardian.com
- CCPA mmsDomain is changed to sourcepoint.theguardian.com
- TCFv2 + CCPA scripts are served through sourcepoint.theguardian.com

[sp-doc]: https://documentation.sourcepoint.com/web-implementation/sourcepoint-gdpr-and-tcf-v2-support/combined-sourcepoint-ccpa-and-gdpr-tcfv2-code

## How to test

The CMP should work as previously.

## How can we measure success?

On Safari, cookies are set server-side and should last longer than 7 days.

## Have we considered potential risks?

Having control of the domain serving external scripts is more secure.

## Images
n/a

### CODE REVIEW

**Comment by sndrs** [comment]
oooooh good spot. did you just notice it or were we told?

**Review by sndrs — APPROVED** [review]

**Comment by mxdvl** [comment]
I knew this was an upcoming change. The latests is that the `baseEndpoint` should be supported in CCPA by the end of the week, too, so will wait until that's done to update this PR.

**Review by sndrs — APPROVED** [review]

**Comment by mxdvl** [comment]
This does not look like it’s going to happen just yet for CCPA, so merging away.

**Comment by mxdvl** [comment]
`baseEndpoint` introduced to CCPA in #343

**Pull request merged**
