### PR TITLE
remove after moving cmp to libs

### PR DESCRIPTION
**Pull request by vlkerag**

### CODE REVIEW

**Comment by akinsola-guardian** [comment]
We should probably remove all traces of coverage listed below.

https://github.com/guardian/consent-management-platform/blob/3b21de4a2bd11d4b15976c610613940e76b88e33/.eslintrc.js#L13

https://github.com/guardian/consent-management-platform/blob/3b21de4a2bd11d4b15976c610613940e76b88e33/.gitignore#L18

**Comment by akinsola-guardian** [comment]
Do we still need the CHANGELOG? 

https://github.com/guardian/consent-management-platform/blob/deletecmp/CHANGELOG.md

**Comment by vlkerag** [comment]
> We should probably remove all traces of coverage listed below.
> 
> https://github.com/guardian/consent-management-platform/blob/3b21de4a2bd11d4b15976c610613940e76b88e33/.eslintrc.js#L13
> 
> https://github.com/guardian/consent-management-platform/blob/3b21de4a2bd11d4b15976c610613940e76b88e33/.gitignore#L18

Removed

**Comment by vlkerag** [comment]
> Do we still need the CHANGELOG?
> 
> https://github.com/guardian/consent-management-platform/blob/deletecmp/CHANGELOG.md

Removed

**Review by akinsola-guardian — APPROVED** [review]
Thanks for this. Looks good. I tested locally and in CODE.

**Pull request merged**
